// Zodiac signs for filtering
export const ZODIAC_SIGNS = [
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpius",
  "Sagittarius",
  "Capricornus",
  "Aquarius",
  "Pisces",
] as const;

export type ZodiacSign = (typeof ZODIAC_SIGNS)[number];

// Interests for profile matching and filtering
export const INTERESTS = [
  "Travel",
  "Cooking",
  "Hiking",
  "Yoga",
  "Gaming",
  "Movies",
  "Music",
  "Photography",
  "Pets",
  "Painting",
  "Art",
  "Fitness",
  "Reading",
  "Dancing",
  "Sports",
  "Board Games",
  "Technology",
  "Fashion",
  "Motorcycling",
  "Science",
  "History",
  "Nature",
  "Adventure",
  "Gardening",
  "Foodie",
  "Writing",
  "Poetry",
  "Astronomy",
  "Sustainable Living",
  "Film Production",
  "Meditation",
  "Comedy",
  "Volunteering",
  "DIY Projects",
  "Art History",
  "Philosophy",
  "Snowboarding",
  "Wine Tasting",
  "Collectibles",
  "Sailing",
  "Karaoke",
  "Surfing",
  "Scuba Diving",
  "Skydiving",
  "Pottery",
  "Wildlife Conservation",
  "Ghost Hunting",
  "Geocaching",
  "Stand-up Comedy",
  "Motor Racing",
  "Paranormal Investigation",
] as const;

export type Interest = (typeof INTERESTS)[number];

// Interest emojis for display
export const INTEREST_EMOJIS: Record<string, string> = {
  Travel: "✈️",
  Cooking: "🍳",
  Hiking: "🥾",
  Yoga: "🧘",
  Gaming: "🎮",
  Movies: "🎬",
  Music: "🎵",
  Photography: "📷",
  Pets: "🐕",
  Painting: "🎨",
  Art: "🎭",
  Fitness: "💪",
  Reading: "📚",
  Dancing: "💃",
  Sports: "🏀",
  "Board Games": "🎲",
  Technology: "📱",
  Fashion: "👗",
  Motorcycling: "🏍️",
  Science: "🔬",
  History: "📜",
  Nature: "🌿",
  Adventure: "🗺️",
  Gardening: "🌱",
  Foodie: "🍽️",
  Writing: "✍️",
  Poetry: "📝",
  Astronomy: "🔭",
  "Sustainable Living": "🌱",
  "Film Production": "🎥",
  Meditation: "🧘",
  Comedy: "😂",
  Volunteering: "💛",
  "DIY Projects": "🔧",
  "Art History": "🏛️",
  Philosophy: "🤔",
  Snowboarding: "🏂",
  "Wine Tasting": "🍷",
  Collectibles: "🎯",
  Sailing: "⛵",
  Karaoke: "🎤",
  Surfing: "🏄",
  "Scuba Diving": "🤿",
  Skydiving: "🪂",
  Pottery: "🏺",
  "Wildlife Conservation": "🦁",
  "Ghost Hunting": "👻",
  Geocaching: "📍",
  "Stand-up Comedy": "🎤",
  "Motor Racing": "🏎️",
  "Paranormal Investigation": "👽",
};
