// 50 Male Gen-Z Profiles
export const GENZ_MALE_PROFILES = [
  {
    name: "Kai Chen",
    gender: "male" as const,
    age: 21,
    zodiacSign: "Aquarius",
    occupation: "Software Dev / Streamer",
    bio: "i code by day and get destroyed in valorant by night. looking for someone who wont roast my kda... jk i can take it",
    interests: ["Gaming", "Coding", "Streaming", "Anime", "Tech"],
    personalityTraits: ["Gamer", "Nerdy", "Chill", "Soft Boy"],
    mbtiType: "INTP",
    relationshipGoal: "player 2 vibes",
  },
  {
    name: "River Park",
    gender: "male" as const,
    age: 20,
    zodiacSign: "Pisces",
    occupation: "Music Producer",
    bio: "i make beats that slap (allegedly). soundcloud link incoming. looking for my muse or at least someone with good taste",
    interests: ["Music Production", "Lo-fi", "Anime", "Gaming", "Art"],
    personalityTraits: ["Creative", "Chill", "Artistic", "Lowkey"],
    mbtiType: "INFP",
    relationshipGoal: "someone to vibe with",
  },
  {
    name: "Axel Rodriguez",
    gender: "male" as const,
    age: 22,
    zodiacSign: "Leo",
    occupation: "Fitness Influencer",
    bio: "gym bro but make it wholesome. i lift heavy and cry at pixar movies. looking for gym partner who becomes more",
    interests: ["Fitness", "Gym", "Nutrition", "Anime", "Gaming"],
    personalityTraits: ["Golden Retriever Energy", "Buff", "Wholesome", "Hype"],
    mbtiType: "ESFP",
    relationshipGoal: "gym couple goals",
  },
  {
    name: "Zion Williams",
    gender: "male" as const,
    age: 19,
    zodiacSign: "Sagittarius",
    occupation: "Content Creator",
    bio: "i make tiktoks for a living and my parents still ask when im getting a real job. chaotic energy only",
    interests: ["TikTok", "Comedy", "Skating", "Fashion", "Memes"],
    personalityTraits: ["Chaotic", "Funny", "Main Character", "Unhinged"],
    mbtiType: "ENTP",
    relationshipGoal: "someone to feature in my videos",
  },
  {
    name: "Milo Kim",
    gender: "male" as const,
    age: 23,
    zodiacSign: "Virgo",
    occupation: "UX Designer",
    bio: "i design apps and have opinions about fonts. type nerd energy. looking for someone who appreciates good kerning",
    interests: ["Design", "Tech", "Typography", "Coffee", "Minimalism"],
    personalityTraits: ["Detail Oriented", "Creative", "Clean Boy", "Lowkey"],
    mbtiType: "INTJ",
    relationshipGoal: "aesthetically pleasing relationship",
  },
  {
    name: "Felix Santos",
    gender: "male" as const,
    age: 21,
    zodiacSign: "Gemini",
    occupation: "Barista / DJ",
    bio: "i make coffee and beats. sometimes at the same time. chaotic neutral energy. looking for someone to close out the bar with",
    interests: ["DJ", "Music", "Coffee", "Nightlife", "Festivals"],
    personalityTraits: ["Chaotic", "Creative", "Night Owl", "Vibey"],
    mbtiType: "ENFP",
    relationshipGoal: "festival romance that lasts",
  },
  {
    name: "Theo Nguyen",
    gender: "male" as const,
    age: 20,
    zodiacSign: "Cancer",
    occupation: "Film Student",
    bio: "i make short films and pretend theyre deep. a24 stan account energy. looking for someone to watch criterion with",
    interests: ["Film", "Cinema", "Photography", "Music", "Art"],
    personalityTraits: ["Film Bro", "Sensitive", "Creative", "Pretentious"],
    mbtiType: "INFP",
    relationshipGoal: "movie marathon partner",
  },
  {
    name: "Jasper Lee",
    gender: "male" as const,
    age: 22,
    zodiacSign: "Scorpio",
    occupation: "Tattoo Artist",
    bio: "i put permanent art on people and somehow they trust me. covered in my own mistakes (tattoos). looking for my muse",
    interests: ["Tattoos", "Art", "Music", "Motorcycles", "Vintage"],
    personalityTraits: ["Artistic", "Mysterious", "Intense", "E-boy"],
    mbtiType: "ISTP",
    relationshipGoal: "someone worth tattooing",
  },
  {
    name: "Atlas Martinez",
    gender: "male" as const,
    age: 19,
    zodiacSign: "Aries",
    occupation: "Skater / Student",
    bio: "i skate and fall. mostly fall tbh. but i look cool doing it sometimes. looking for someone to film my tricks",
    interests: ["Skating", "Fashion", "Music", "Photography", "Street Art"],
    personalityTraits: ["Chill", "Adventurous", "Skater Boy", "Lowkey"],
    mbtiType: "ISTP",
    relationshipGoal: "skate park love story",
  },
  {
    name: "Orion Wright",
    gender: "male" as const,
    age: 23,
    zodiacSign: "Aquarius",
    occupation: "Space Science Student",
    bio: "space nerd who will infodump about black holes. looking for someone who thinks the cosmos is as cool as i do",
    interests: ["Astronomy", "Space", "Science", "Sci-Fi", "Gaming"],
    personalityTraits: ["Nerdy", "Curious", "Deep", "Enthusiastic"],
    mbtiType: "INTP",
    relationshipGoal: "stargazing forever",
  },
  {
    name: "Phoenix Park",
    gender: "male" as const,
    age: 21,
    zodiacSign: "Leo",
    occupation: "Fashion Design Student",
    bio: "i thrift and customize everything. if it aint unique i dont want it. looking for someone with immaculate style",
    interests: ["Fashion", "Thrifting", "Design", "Art", "Photography"],
    personalityTraits: ["Stylish", "Creative", "Confident", "Artistic"],
    mbtiType: "ENFP",
    relationshipGoal: "best dressed couple",
  },
  {
    name: "Ryder Chen",
    gender: "male" as const,
    age: 20,
    zodiacSign: "Capricorn",
    occupation: "Finance Bro / Gamer",
    bio: "by day i look at spreadsheets. by night i rage at league. perfectly balanced. looking for someone who gets both sides",
    interests: ["Finance", "Gaming", "Investing", "Gym", "Strategy"],
    personalityTraits: ["Ambitious", "Competitive", "Gamer", "Driven"],
    mbtiType: "ENTJ",
    relationshipGoal: "power couple who games together",
  },
  {
    name: "Sage Williams",
    gender: "male" as const,
    age: 22,
    zodiacSign: "Taurus",
    occupation: "Plant Dad / Freelancer",
    bio: "i have 30 plants and treat them better than myself. cottagecore bf application. looking for someone to garden with",
    interests: ["Plants", "Gardening", "Nature", "Cooking", "Cozy Vibes"],
    personalityTraits: ["Plant Dad", "Nurturing", "Grounded", "Wholesome"],
    mbtiType: "ISFJ",
    relationshipGoal: "domestic bliss",
  },
  {
    name: "Wolf Thompson",
    gender: "male" as const,
    age: 19,
    zodiacSign: "Scorpio",
    occupation: "Music Student",
    bio: "i play guitar and write sad songs about people i made up. delulu but in a hot way. looking for lyrical inspiration",
    interests: ["Guitar", "Music", "Songwriting", "Poetry", "Vibes"],
    personalityTraits: ["Brooding", "Artistic", "Romantic", "Mysterious"],
    mbtiType: "INFP",
    relationshipGoal: "love worth writing about",
  },
  {
    name: "Ash Mitchell",
    gender: "male" as const,
    age: 23,
    zodiacSign: "Aries",
    occupation: "Personal Trainer",
    bio: "gym bro who actually listens. i lift heavy things and talk about feelings. emotional availability and gains",
    interests: ["Fitness", "Gym", "Mental Health", "Nutrition", "Hiking"],
    personalityTraits: ["Supportive", "Strong", "Emotional", "Motivating"],
    mbtiType: "ESFJ",
    relationshipGoal: "someone to grow with",
  },
  {
    name: "Storm Davis",
    gender: "male" as const,
    age: 21,
    zodiacSign: "Aquarius",
    occupation: "Environmental Activist",
    bio: "climate warrior who composts and judges ur recycling. vegan btw. looking for eco conscious queen to save the planet",
    interests: [
      "Activism",
      "Environment",
      "Vegan",
      "Sustainability",
      "Protests",
    ],
    personalityTraits: ["Passionate", "Activist", "Lowkey Judgy", "Caring"],
    mbtiType: "INFJ",
    relationshipGoal: "change the world together",
  },
  {
    name: "Blaze Reyes",
    gender: "male" as const,
    age: 20,
    zodiacSign: "Leo",
    occupation: "Dance Student",
    bio: "i learned all the tiktok dances and now its my personality. main character energy. looking for my dance partner",
    interests: ["Dancing", "K-pop", "TikTok", "Fashion", "Performing"],
    personalityTraits: ["Confident", "Energetic", "Performer", "Extra"],
    mbtiType: "ESFP",
    relationshipGoal: "dance couple goals",
  },
  {
    name: "Indigo Kim",
    gender: "male" as const,
    age: 22,
    zodiacSign: "Pisces",
    occupation: "Art Student",
    bio: "i paint my feelings and my feelings are usually chaos. emotionally available artist bf material. looking for my muse",
    interests: ["Art", "Painting", "Museums", "Music", "Deep Talks"],
    personalityTraits: ["Sensitive", "Artistic", "Emotional", "Romantic"],
    mbtiType: "INFP",
    relationshipGoal: "art school romance",
  },
  {
    name: "Nova Santos",
    gender: "male" as const,
    age: 19,
    zodiacSign: "Gemini",
    occupation: "Podcaster / Student",
    bio: "i have a podcast with 5 listeners and theyre all me on different accounts. chaotic storyteller energy",
    interests: ["Podcasting", "Comedy", "Storytelling", "Pop Culture", "Memes"],
    personalityTraits: ["Funny", "Chatty", "Chaotic", "Creative"],
    mbtiType: "ENTP",
    relationshipGoal: "content couple",
  },
  {
    name: "Zen Patel",
    gender: "male" as const,
    age: 23,
    zodiacSign: "Libra",
    occupation: "Yoga Instructor",
    bio: "namaste or whatever. i teach yoga and pretend to have my life together. actually pretty chill tho",
    interests: ["Yoga", "Meditation", "Wellness", "Nature", "Tea"],
    personalityTraits: ["Zen", "Chill", "Balanced", "Spiritual"],
    mbtiType: "INFJ",
    relationshipGoal: "peaceful partnership",
  },
  {
    name: "Hawk Gonzalez",
    gender: "male" as const,
    age: 21,
    zodiacSign: "Aries",
    occupation: "MMA Fighter / Student",
    bio: "i fight people for fun (consensually). scary on the mat, golden retriever everywhere else. dont be intimidated",
    interests: ["MMA", "Fitness", "Fighting", "Movies", "Food"],
    personalityTraits: [
      "Tough",
      "Golden Retriever Energy",
      "Protective",
      "Sweet",
    ],
    mbtiType: "ESTP",
    relationshipGoal: "someone to protect",
  },
  {
    name: "Echo Lee",
    gender: "male" as const,
    age: 20,
    zodiacSign: "Cancer",
    occupation: "Musician",
    bio: "i make sad lo-fi beats at 3am. emotional but in a chill way. looking for someone to share my headphones with",
    interests: ["Music", "Lo-fi", "Production", "Vinyl", "Anime"],
    personalityTraits: ["Soft Boy", "Creative", "Emotional", "Chill"],
    mbtiType: "INFP",
    relationshipGoal: "soundtrack to our love",
  },
  {
    name: "Cruz Martinez",
    gender: "male" as const,
    age: 22,
    zodiacSign: "Sagittarius",
    occupation: "Travel Photographer",
    bio: "i take pics and book flights. backpack life. looking for adventure buddy who becomes more. passport stamps > everything",
    interests: ["Travel", "Photography", "Adventure", "Culture", "Food"],
    personalityTraits: [
      "Adventurous",
      "Free Spirit",
      "Wanderlust",
      "Spontaneous",
    ],
    mbtiType: "ESTP",
    relationshipGoal: "travel the world together",
  },
  {
    name: "Nico Wright",
    gender: "male" as const,
    age: 19,
    zodiacSign: "Virgo",
    occupation: "Comp Sci Student",
    bio: "i code and game. thats it thats the bio. socially awkward king. looking for someone who gets my references",
    interests: ["Coding", "Gaming", "Anime", "Tech", "Memes"],
    personalityTraits: ["Nerdy", "Awkward", "Smart", "Introverted"],
    mbtiType: "INTP",
    relationshipGoal: "someone who gets my references",
  },
  {
    name: "Slate Johnson",
    gender: "male" as const,
    age: 23,
    zodiacSign: "Capricorn",
    occupation: "Architecture Student",
    bio: "i design buildings and have opinions about brutalism. dark academia vibes. looking for good design appreciation",
    interests: ["Architecture", "Design", "History", "Coffee", "Art"],
    personalityTraits: ["Intellectual", "Creative", "Ambitious", "Cultured"],
    mbtiType: "INTJ",
    relationshipGoal: "power couple in turtlenecks",
  },
  {
    name: "Reed Thompson",
    gender: "male" as const,
    age: 21,
    zodiacSign: "Taurus",
    occupation: "Chef / Food Blogger",
    bio: "i cook and photograph food. thats my whole personality. the way to my heart is appreciating my cooking",
    interests: ["Cooking", "Food", "Photography", "Wine", "Farmers Markets"],
    personalityTraits: ["Foodie", "Nurturing", "Creative", "Sensual"],
    mbtiType: "ISFJ",
    relationshipGoal: "cook dinner together forever",
  },
  {
    name: "Flint Davis",
    gender: "male" as const,
    age: 20,
    zodiacSign: "Scorpio",
    occupation: "Psychology Student",
    bio: "i will psychoanalyze u but in a hot way. emotionally intelligent and slightly unhinged. deep connections only",
    interests: ["Psychology", "Philosophy", "Deep Talks", "Books", "Art"],
    personalityTraits: ["Intense", "Deep", "Analytical", "Mysterious"],
    mbtiType: "INFJ",
    relationshipGoal: "soulmate level connection",
  },
  {
    name: "Harbor Kim",
    gender: "male" as const,
    age: 22,
    zodiacSign: "Cancer",
    occupation: "Marine Biology Student",
    bio: "ocean boy who will talk about sea creatures for hours. take me to the beach and ill love u forever",
    interests: ["Ocean", "Marine Life", "Beach", "Surfing", "Environmental"],
    personalityTraits: ["Water Baby", "Caring", "Nature Lover", "Chill"],
    mbtiType: "ISFP",
    relationshipGoal: "beach sunsets forever",
  },
  {
    name: "Cobalt Pham",
    gender: "male" as const,
    age: 19,
    zodiacSign: "Leo",
    occupation: "Theater Student",
    bio: "drama kid who made it a career path. yes i will randomly burst into song. appreciate the performance pls",
    interests: ["Theater", "Acting", "Musicals", "Drama", "Performance"],
    personalityTraits: ["Dramatic", "Expressive", "Confident", "Extra"],
    mbtiType: "ENFP",
    relationshipGoal: "rom com level romance",
  },
  {
    name: "Clay Foster",
    gender: "male" as const,
    age: 23,
    zodiacSign: "Taurus",
    occupation: "Ceramics Artist",
    bio: "i make pottery and pretend im in ghost. hands always dirty with clay. looking for handmade appreciation",
    interests: ["Ceramics", "Art", "Coffee", "Music", "Nature"],
    personalityTraits: ["Artistic", "Grounded", "Patient", "Creative"],
    mbtiType: "ISFP",
    relationshipGoal: "make art together",
  },
  {
    name: "Jett Rodriguez",
    gender: "male" as const,
    age: 21,
    zodiacSign: "Aries",
    occupation: "Extreme Sports Athlete",
    bio: "i do dangerous things for fun and somehow havent died yet. adrenaline junkie looking for someone who keeps up",
    interests: [
      "Extreme Sports",
      "Skateboarding",
      "Surfing",
      "Snowboarding",
      "Adrenaline",
    ],
    personalityTraits: ["Fearless", "Adventurous", "Chaotic", "Energetic"],
    mbtiType: "ESTP",
    relationshipGoal: "adventure partner",
  },
  {
    name: "Onyx Mitchell",
    gender: "male" as const,
    age: 20,
    zodiacSign: "Scorpio",
    occupation: "Graphic Designer",
    bio: "i design things and have too many opinions about it. dark aesthetic. good typography appreciation required",
    interests: ["Design", "Art", "Music", "Fashion", "Dark Aesthetic"],
    personalityTraits: ["Creative", "Opinionated", "Mysterious", "Artistic"],
    mbtiType: "INFP",
    relationshipGoal: "aesthetically matched",
  },
  {
    name: "Sterling Park",
    gender: "male" as const,
    age: 22,
    zodiacSign: "Libra",
    occupation: "Fashion Photographer",
    bio: "i take pretty pictures of pretty people. including u if u swipe right. looking for someone photogenic who vibes",
    interests: ["Photography", "Fashion", "Art", "Travel", "Aesthetic"],
    personalityTraits: ["Artistic", "Charming", "Social", "Creative"],
    mbtiType: "ENFJ",
    relationshipGoal: "muse and photographer",
  },
  {
    name: "Pike Williams",
    gender: "male" as const,
    age: 19,
    zodiacSign: "Sagittarius",
    occupation: "Adventure Guide / Student",
    bio: "i take people on hikes and try not to get them lost. outdoorsy but still chronically online. best of both",
    interests: ["Hiking", "Camping", "Nature", "Adventure", "Photography"],
    personalityTraits: ["Adventurous", "Guide Energy", "Chill", "Outdoorsy"],
    mbtiType: "ESTP",
    relationshipGoal: "explore together",
  },
  {
    name: "Cove Chen",
    gender: "male" as const,
    age: 23,
    zodiacSign: "Pisces",
    occupation: "Writer",
    bio: "i write stories and pretend people will read them someday. emotionally available writer bf era. need inspiration",
    interests: ["Writing", "Reading", "Coffee Shops", "Poetry", "Deep Talks"],
    personalityTraits: ["Creative", "Sensitive", "Romantic", "Dreamy"],
    mbtiType: "INFP",
    relationshipGoal: "novel worthy love",
  },
  {
    name: "Ridge Santos",
    gender: "male" as const,
    age: 21,
    zodiacSign: "Capricorn",
    occupation: "Rock Climbing Instructor",
    bio: "i climb rocks and teach others to climb rocks. simple life. looking for belay partner who becomes life partner",
    interests: ["Rock Climbing", "Bouldering", "Hiking", "Fitness", "Outdoors"],
    personalityTraits: ["Strong", "Patient", "Supportive", "Adventurous"],
    mbtiType: "ISTP",
    relationshipGoal: "climb together",
  },
  {
    name: "West Lee",
    gender: "male" as const,
    age: 20,
    zodiacSign: "Gemini",
    occupation: "Stand-up Comic / Student",
    bio: "i do comedy and cope through humor. will make u laugh or die trying. looking for unhinged joke appreciation",
    interests: ["Comedy", "Stand-up", "Memes", "Writing", "Movies"],
    personalityTraits: ["Funny", "Chaotic", "Self-Deprecating", "Quick-Witted"],
    mbtiType: "ENTP",
    relationshipGoal: "someone who laughs at my jokes",
  },
  {
    name: "Marsh Thompson",
    gender: "male" as const,
    age: 22,
    zodiacSign: "Cancer",
    occupation: "Veterinary Student",
    bio: "future vet who cries at animal rescue videos. golden retriever bf energy but actually with golden retrievers",
    interests: ["Animals", "Veterinary", "Nature", "Dogs", "Wholesome Content"],
    personalityTraits: [
      "Nurturing",
      "Soft",
      "Caring",
      "Golden Retriever Energy",
    ],
    mbtiType: "ISFJ",
    relationshipGoal: "adopt dogs together",
  },
  {
    name: "Birch Nguyen",
    gender: "male" as const,
    age: 19,
    zodiacSign: "Virgo",
    occupation: "Barista / Music Student",
    bio: "i make coffee and play bass. both require patience apparently. good espresso and bad pun appreciation needed",
    interests: ["Coffee", "Music", "Bass", "Jazz", "Vinyl"],
    personalityTraits: ["Chill", "Musical", "Reliable", "Lowkey"],
    mbtiType: "ISFP",
    relationshipGoal: "coffee date that never ends",
  },
  {
    name: "Stone Davis",
    gender: "male" as const,
    age: 23,
    zodiacSign: "Taurus",
    occupation: "Furniture Maker",
    bio: "i build things with my hands. simple man with simple pleasures. craftsmanship and bad dad jokes appreciation",
    interests: ["Woodworking", "Building", "Design", "Nature", "Coffee"],
    personalityTraits: ["Handy", "Grounded", "Patient", "Reliable"],
    mbtiType: "ISTP",
    relationshipGoal: "build a life together literally",
  },
  {
    name: "Vale Martinez",
    gender: "male" as const,
    age: 21,
    zodiacSign: "Libra",
    occupation: "Wine Student / Sommelier",
    bio: "i know too much about wine for someone my age. will pair wine with ur mood. looking for tasting room dates",
    interests: ["Wine", "Food", "Travel", "Cooking", "Fancy Things"],
    personalityTraits: ["Cultured", "Romantic", "Sophisticated", "Chill"],
    mbtiType: "ISFJ",
    relationshipGoal: "wine and dine forever",
  },
  {
    name: "Ember Wright",
    gender: "male" as const,
    age: 20,
    zodiacSign: "Aries",
    occupation: "Firefighter / EMT Student",
    bio: "future first responder. hero complex maybe. will save ur life and make bad jokes about it after",
    interests: ["Fitness", "First Aid", "Community", "Gaming", "Cooking"],
    personalityTraits: ["Brave", "Protective", "Funny", "Caring"],
    mbtiType: "ESFJ",
    relationshipGoal: "someone worth coming home to",
  },
  {
    name: "Canyon Kim",
    gender: "male" as const,
    age: 22,
    zodiacSign: "Sagittarius",
    occupation: "National Park Guide",
    bio: "i live in a van and work at national parks. literally touch grass for a living. wanderlust partner needed",
    interests: [
      "National Parks",
      "Van Life",
      "Hiking",
      "Photography",
      "Nature",
    ],
    personalityTraits: ["Free Spirit", "Adventurous", "Nomadic", "Grounded"],
    mbtiType: "ISFP",
    relationshipGoal: "van life together",
  },
  {
    name: "Drift Patel",
    gender: "male" as const,
    age: 19,
    zodiacSign: "Aquarius",
    occupation: "Robotics Student",
    bio: "i build robots and talk to them more than humans sometimes. nerd energy. looking for robot appreciation",
    interests: ["Robotics", "Engineering", "Sci-Fi", "Gaming", "Tech"],
    personalityTraits: ["Nerdy", "Innovative", "Awkward", "Passionate"],
    mbtiType: "INTP",
    relationshipGoal: "build the future together",
  },
  {
    name: "Moss Johnson",
    gender: "male" as const,
    age: 23,
    zodiacSign: "Cancer",
    occupation: "Florist",
    bio: "yes im a guy florist. yes i will bring u flowers. looking for plant appreciation and feminine side acceptance",
    interests: ["Flowers", "Plants", "Nature", "Art", "Cozy Vibes"],
    personalityTraits: ["Nurturing", "Artistic", "Soft", "Romantic"],
    mbtiType: "ISFJ",
    relationshipGoal: "bring flowers every week",
  },
  {
    name: "Blade Santos",
    gender: "male" as const,
    age: 21,
    zodiacSign: "Scorpio",
    occupation: "Sushi Chef",
    bio: "i cut fish professionally and look intimidating doing it. soft inside though. looking for omakase appreciation",
    interests: ["Cooking", "Japanese Culture", "Sushi", "Knives", "Food"],
    personalityTraits: ["Skilled", "Mysterious", "Passionate", "Perfectionist"],
    mbtiType: "ISTP",
    relationshipGoal: "someone to cook for",
  },
  {
    name: "Rune Lee",
    gender: "male" as const,
    age: 20,
    zodiacSign: "Pisces",
    occupation: "Game Developer",
    bio: "i make indie games that 12 people play. one day ill blow up or give up. looking for player 2 who believes",
    interests: ["Game Dev", "Gaming", "Pixel Art", "Music", "Anime"],
    personalityTraits: ["Creative", "Dreamer", "Nerdy", "Determined"],
    mbtiType: "INFP",
    relationshipGoal: "someone in my credits",
  },
];
